name: Run Unit Test Framework
on:
    pull_request:
      paths: 
        - src/**
        - tests/**
        - pyproject.toml
jobs: 

  run_test_suite:
    runs-on: ubuntu-latest

    steps: 

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Test Suite
        run: |
          sudo apt install python3
          sudo apt install pip 
          pip install requirements.txt
          python3 -m unittest tests/test_workspaces.py  -v 